const words_countries = [
    { base: "afghanistan", variants: ["afghanistan"] },
    { base: "albania", variants: ["albania"] },
    { base: "algeria", variants: ["algeria"] },
    { base: "andorra", variants: ["andorra"] },
    { base: "angola", variants: ["angola"] },
    { base: "antigua and barbuda", variants: ["antigua and barbuda", "antigua"] },
    { base: "argentina", variants: ["argentina"] },
    { base: "armenia", variants: ["armenia"] },
    { base: "australia", variants: ["australia"] },
    { base: "austria", variants: ["austria"] },
    { base: "azerbaijan", variants: ["azerbaijan"] },
    { base: "bahamas", variants: ["bahamas", "the bahamas"] },
    { base: "bahrain", variants: ["bahrain"] },
    { base: "bangladesh", variants: ["bangladesh"] },
    { base: "barbados", variants: ["barbados"] },
    { base: "belarus", variants: ["belarus", "belarus republic"] },
    { base: "belgium", variants: ["belgium"] },
    { base: "belize", variants: ["belize"] },
    { base: "benin", variants: ["benin"] },
    { base: "bhutan", variants: ["bhutan"] },
    { base: "bolivia", variants: ["bolivia", "bolivia plurinational state of"] },
    { base: "bosnia and herzegovina", variants: ["bosnia and herzegovina", "bosnia"] },
    { base: "botswana", variants: ["botswana"] },
    { base: "brazil", variants: ["brazil", "brazil federative republic"] },
    { base: "brunei", variants: ["brunei", "brunei darussalam"] },
    { base: "bulgaria", variants: ["bulgaria"] },
    { base: "burkina faso", variants: ["burkina faso", "burkina"] },
    { base: "burundi", variants: ["burundi"] },
    { base: "cambodia", variants: ["cambodia", "kingdom of cambodia"] },
    { base: "cameroon", variants: ["cameroon"] },
    { base: "canada", variants: ["canada"] },
    { base: "cape verde", variants: ["cape verde", "cabo verde"] },
    { base: "central african republic", variants: ["central african republic", "central africa"] },
    { base: "chad", variants: ["chad"] },
    { base: "chile", variants: ["chile"] },
    { base: "china", variants: ["china", "people's republic of china"] },
    { base: "colombia", variants: ["colombia"] },
    { base: "comoros", variants: ["comoros", "the comoros"] },
    { base: "congo", variants: ["congo", "republic of congo", "congo-brazzaville"] },
    { base: "democratic republic of the congo", variants: ["democratic republic of the congo", "dr congo", "congo-kinshasa"] },
    { base: "costa rica", variants: ["costa rica"] },
    { base: "côte d'ivoire", variants: ["côte d'ivoire", "ivory coast", "cote d'ivoire"] },
    { base: "croatia", variants: ["croatia", "republic of croatia"] },
    { base: "cuba", variants: ["cuba"] },
    { base: "cyprus", variants: ["cyprus"] },
    { base: "czechia", variants: ["czechia", "czech republic"] },
    { base: "denmark", variants: ["denmark"] },
    { base: "djibouti", variants: ["djibouti"] },
    { base: "dominica", variants: ["dominica"] },
    { base: "dominican republic", variants: ["dominican republic"] },
    { base: "ecuador", variants: ["ecuador"] },
    { base: "egypt", variants: ["egypt", "arab republic of egypt"] },
    { base: "el salvador", variants: ["el salvador", "salvador"] },
    { base: "equatorial guinea", variants: ["equatorial guinea", "guinea equatorial"] },
    { base: "eritrea", variants: ["eritrea"] },
    { base: "estonia", variants: ["estonia"] },
    { base: "eswatini", variants: ["eswatini", "swaziland"] },
    { base: "ethiopia", variants: ["ethiopia"] },
    { base: "fiji", variants: ["fiji"] },
    { base: "finland", variants: ["finland"] },
    { base: "france", variants: ["france"] },
    { base: "gabon", variants: ["gabon"] },
    { base: "gambia", variants: ["gambia", "the gambia"] },
    { base: "georgia", variants: ["georgia"] },
    { base: "germany", variants: ["germany", "federal republic of germany"] },
    { base: "ghana", variants: ["ghana"] },
    { base: "greece", variants: ["greece", "hellas"] },
    { base: "grenada", variants: ["grenada"] },
    { base: "guatemala", variants: ["guatemala"] },
    { base: "guinea", variants: ["guinea"] },
    { base: "guinea-bissau", variants: ["guinea-bissau"] },
    { base: "guyana", variants: ["guyana"] },
    { base: "haiti", variants: ["haiti", "haiti republic"] },
    { base: "honduras", variants: ["honduras"] },
    { base: "hungary", variants: ["hungary", "hungarian republic"] },
    { base: "iceland", variants: ["iceland"] },
    { base: "india", variants: ["india"] },
    { base: "indonesia", variants: ["indonesia"] },
    { base: "iran", variants: ["iran", "islamic republic of iran"] },
    { base: "iraq", variants: ["iraq"] },
    { base: "ireland", variants: ["ireland"] },
    { base: "israel", variants: ["israel"] },
    { base: "italy", variants: ["italy", "republic of italy"] },
    { base: "jamaica", variants: ["jamaica"] },
    { base: "japan", variants: ["japan", "nippon", "nihon"] },
    { base: "jordan", variants: ["jordan"] },
    { base: "kazakhstan", variants: ["kazakhstan"] },
    { base: "kenya", variants: ["kenya"] },
    { base: "kiribati", variants: ["kiribati"] },
    { base: "kuwait", variants: ["kuwait"] },
    { base: "kyrgyzstan", variants: ["kyrgyzstan"] },
    { base: "laos", variants: ["laos", "lao people's democratic republic"] },
    { base: "latvia", variants: ["latvia"] },
    { base: "lebanon", variants: ["lebanon"] },
    { base: "lesotho", variants: ["lesotho"] },
    { base: "liberia", variants: ["liberia"] },
    { base: "libya", variants: ["libya", "libyan arab jamahiriya"] },
    { base: "liechtenstein", variants: ["liechtenstein"] },
    { base: "lithuania", variants: ["lithuania"] },
    { base: "luxembourg", variants: ["luxembourg"] },
    { base: "madagascar", variants: ["madagascar"] },
    { base: "malawi", variants: ["malawi"] },
    { base: "malaysia", variants: ["malaysia"] },
    { base: "maldives", variants: ["maldives", "maldives republic"] },
    { base: "mali", variants: ["mali"] },
    { base: "malta", variants: ["malta"] },
    { base: "marshall islands", variants: ["marshall islands", "marshall islands republic"] },
    { base: "mauritania", variants: ["mauritania"] },
    { base: "mauritius", variants: ["mauritius"] },
    { base: "mexico", variants: ["mexico", "mexican united states"] },
    { base: "micronesia", variants: ["micronesia", "federated states of micronesia"] },
    { base: "moldova", variants: ["moldova", "republic of moldova"] },
    { base: "monaco", variants: ["monaco"] },
    { base: "mongolia", variants: ["mongolia", "mongol republic"] },
    { base: "montenegro", variants: ["montenegro"] },
    { base: "morocco", variants: ["morocco", "kingdom of morocco"] },
    { base: "mozambique", variants: ["mozambique"] },
    { base: "myanmar", variants: ["myanmar", "burma"] },
    { base: "namibia", variants: ["namibia"] },
    { base: "nauru", variants: ["nauru"] },
    { base: "nepal", variants: ["nepal"] },
    { base: "netherlands", variants: ["netherlands", "holland"] },
    { base: "new zealand", variants: ["new zealand"] },
    { base: "nicaragua", variants: ["nicaragua"] },
    { base: "niger", variants: ["niger"] },
    { base: "nigeria", variants: ["nigeria"] },
    { base: "north korea", variants: ["north korea", "korea, democratic people's republic of", "democratic people's republic of korea"] },
    { base: "north macedonia", variants: ["north macedonia", "macedonia"] },
    { base: "norway", variants: ["norway"] },
    { base: "oman", variants: ["oman"] },
    { base: "pakistan", variants: ["pakistan"] },
    { base: "palau", variants: ["palau"] },
    { base: "palestine", variants: ["palestine", "state of palestine"] },
    { base: "panama", variants: ["panama"] },
    { base: "papua new guinea", variants: ["papua new guinea"] },
    { base: "paraguay", variants: ["paraguay"] },
    { base: "peru", variants: ["peru"] },
    { base: "philippines", variants: ["philippines"] },
    { base: "poland", variants: ["poland", "republic of poland"] },
    { base: "portugal", variants: ["portugal"] },
    { base: "qatar", variants: ["qatar"] },
    { base: "romania", variants: ["romania"] },
    { base: "russia", variants: ["russia", "russian federation"] },
    { base: "rwanda", variants: ["rwanda"] },
    { base: "saint kitts and nevis", variants: ["saint kitts and nevis", "s.kitts and n. vis"] },
    { base: "saint lucia", variants: ["saint lucia", "st. lucia"] },
    { base: "saint vincent and the grenadines", variants: ["saint vincent and the grenadines", "st. vincent and the grenadines"] },
    { base: "samoa", variants: ["samoa", "independent state of samoa"] },
    { base: "san marino", variants: ["san marino"] },
    { base: "sao tome and principe", variants: ["sao tome and principe", "sao tome & principe"] },
    { base: "saudi arabia", variants: ["saudi arabia"] },
    { base: "senegal", variants: ["senegal"] },
    { base: "serbia", variants: ["serbia", "republic of serbia"] },
    { base: "seychelles", variants: ["seychelles"] },
    { base: "sierra leone", variants: ["sierra leone"] },
    { base: "singapore", variants: ["singapore"] },
    { base: "slovakia", variants: ["slovakia", "slovak republic"] },
    { base: "slovenia", variants: ["slovenia"] },
    { base: "solomon islands", variants: ["solomon islands"] },
    { base: "somalia", variants: ["somalia"] },
    { base: "south africa", variants: ["south africa", "republic of south africa"] },
    { base: "south korea", variants: ["south korea", "korea, republic of", "republic of korea"] },
    { base: "south sudan", variants: ["south sudan"] },
    { base: "spain", variants: ["spain", "kingdom of spain"] },
    { base: "sri lanka", variants: ["sri lanka", "republic of sri lanka"] },
    { base: "sudan", variants: ["sudan", "sudanese arab republic"] },
    { base: "suriname", variants: ["suriname"] },
    { base: "sweden", variants: ["sweden"] },
    { base: "switzerland", variants: ["switzerland", "swiss confederation"] },
    { base: "syria", variants: ["syria", "syrian arab republic"] },
    { base: "taiwan", variants: ["taiwan", "republic of china (taiwan)"] },
    { base: "tajikistan", variants: ["tajikistan"] },
    { base: "tanzania", variants: ["tanzania", "tanzania, united republic of"] },
    { base: "thailand", variants: ["thailand"] },
    { base: "timor-leste", variants: ["timor-leste", "east timor"] },
    { base: "togo", variants: ["togo"] },
    { base: "tonga", variants: ["tonga"] },
    { base: "trinidad and tobago", variants: ["trinidad and tobago", "trinidad & tobago"] },
    { base: "tunisia", variants: ["tunisia", "tunisian republic"] },
    { base: "turkey", variants: ["turkey", "republic of turkey"] },
    { base: "turkmenistan", variants: ["turkmenistan"] },
    { base: "tuvalu", variants: ["tuvalu"] },
    { base: "uganda", variants: ["uganda"] },
    { base: "ukraine", variants: ["ukraine"] },
    { base: "united arab emirates", variants: ["united arab emirates", "uae"] },
    { base: "united kingdom", variants: ["united kingdom", "uk", "great britain"] },
    { base: "united states", variants: ["united states", "usa", "us", "united states of america"] },
    { base: "uruguay", variants: ["uruguay"] },
    { base: "uzbekistan", variants: ["uzbekistan"] },
    { base: "vanuatu", variants: ["vanuatu"] },
    { base: "vatican city", variants: ["vatican city", "holy see"] },
    { base: "venezuela", variants: ["venezuela", "bolivarian republic of venezuela"] },
    { base: "vietnam", variants: ["vietnam", "viet nam"] },
    { base: "yemen", variants: ["yemen", "republic of yemen"] },
    { base: "zambia", variants: ["zambia"] },
    { base: "zimbabwe", variants: ["zimbabwe"] }
];
